# Generated by Django 5.2.5 on 2025-08-27 19:45

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('project_description', models.TextField(verbose_name='Descrição do Projeto')),
                ('attachment', models.FileField(blank=True, help_text='Arquivo opcional (PDF, DOC, DOCX, TXT - máx. 10MB)', null=True, upload_to=main.models.contact_file_upload_path, verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre o contato', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('notification_email', models.EmailField(default='admin@example.com', max_length=254, verbose_name='Email para Notificações')),
                ('auto_reply_enabled', models.BooleanField(default=True, verbose_name='Resposta Automática')),
                ('auto_reply_subject', models.CharField(default='Obrigado pelo seu contato!', max_length=200, verbose_name='Assunto da Resposta Automática')),
                ('auto_reply_message', models.TextField(default='Olá {name},\n\nObrigado por entrar em contato conosco!\n\nRecebemos sua mensagem e retornaremos em breve. Nosso tempo de resposta é de até 2 horas durante o horário comercial.\n\nDetalhes da sua mensagem:\n- Nome: {name}\n- Email: {email}\n- WhatsApp: {whatsapp}\n- Data: {date}\n\nAtenciosamente,\nEquipe DevPro', verbose_name='Mensagem da Resposta Automática')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='Tamanho Máximo do Arquivo (MB)')),
                ('allowed_file_types', models.CharField(default='pdf,doc,docx,txt', help_text='Separados por vírgula (ex: pdf,doc,docx,txt)', max_length=200, verbose_name='Tipos de Arquivo Permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Formulário',
                'verbose_name_plural': 'Configurações do Formulário',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total de Visualizações')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Visitantes Únicos')),
                ('contact_submissions', models.PositiveIntegerField(default=0, verbose_name='Envios de Contato')),
                ('top_country_1', models.CharField(blank=True, max_length=100, verbose_name='País #1')),
                ('top_country_1_count', models.PositiveIntegerField(default=0, verbose_name='Contagem País #1')),
                ('top_country_2', models.CharField(blank=True, max_length=100, verbose_name='País #2')),
                ('top_country_2_count', models.PositiveIntegerField(default=0, verbose_name='Contagem País #2')),
                ('top_country_3', models.CharField(blank=True, max_length=100, verbose_name='País #3')),
                ('top_country_3_count', models.PositiveIntegerField(default=0, verbose_name='Contagem País #3')),
                ('desktop_views', models.PositiveIntegerField(default=0, verbose_name='Visualizações Desktop')),
                ('mobile_views', models.PositiveIntegerField(default=0, verbose_name='Visualizações Mobile')),
                ('tablet_views', models.PositiveIntegerField(default=0, verbose_name='Visualizações Tablet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estatística do Site',
                'verbose_name_plural': 'Estatísticas do Site',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referrer')),
                ('page_url', models.URLField(default='/', verbose_name='URL da Página')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Região/Estado')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Navegador')),
                ('operating_system', models.CharField(blank=True, max_length=50, verbose_name='Sistema Operacional')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Sessão')),
                ('time_on_page', models.PositiveIntegerField(default=0, verbose_name='Tempo na Página (segundos)')),
            ],
            options={
                'verbose_name': 'Visualização de Página',
                'verbose_name_plural': 'Visualizações de Página',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='main_pagevi_timesta_a4df72_idx'), models.Index(fields=['ip_address'], name='main_pagevi_ip_addr_eebeba_idx'), models.Index(fields=['country'], name='main_pagevi_country_239e87_idx')],
            },
        ),
    ]
